### ISSUE TITLE
Refactor to View Controller instead of action sheet

### ISSUE THREAD

**Issue by Haud** [prolificinteractive/Yoshi#16]
I think it would be beneficial if, instead of an action sheet, we presented a view controller / window or something instead. It would allow for a nicer looking UI; Android has something similar for debugging and its cool. I just think that if we stick with action sheet and encourage people to add as many debug options as necessary, an action sheet will cease to be adequate.

**Comment by MichaelCampbell** [comment]
Resolved with #21
