### ISSUE TITLE
Show which option is currently selected

### ISSUE THREAD

**Issue by hkellaway** [prolificinteractive/Yoshi#20]
e.g. if i'm switching environments and i'm currently on Staging, i'd like to see this highlighted in some way

**Comment by hkellaway** [comment]
also, if the current option is reselected, the callback shouldn't be called

**Comment by cassiewallace** [comment]
Can we prioritize this? We're working on Checkout now and I want to make sure testers are aware if they are going to submit a real order.

**Comment by MichaelCampbell** [comment]
This has been resolved with #31
