### ISSUE TITLE
Debug view controller should show device-specific icon.

### ISSUE THREAD

**Issue by htinlinn** [prolificinteractive/Yoshi#27]
It would be nice if the debug view controller could pick out the correct icon based on the device type instead of always choosing the first icon in the bundle.

**Comment by MichaelCampbell** [comment]
@htinlinn do we still need this? We did change this to use the last icon, which is usually larger

**Comment by htinlinn** [comment]
@MichaelCampbell nope. that should fix it.

**Comment by MichaelCampbell** [comment]
Closing as this is no longer an issue
