### ISSUE TITLE
Make YoshiTableViewMenuItem has the ability to execute after dismissal 

### ISSUE THREAD

**Issue by ghvg1313** [prolificinteractive/Yoshi#51]

**Comment by quentinR** [comment]
@ghvg1313 Can you provide a little bit more details please? Thanks!

**Comment by ghvg1313** [comment]
I don't know if this is a common use case, back in SoulCycle we had a feature story need to be verified by PM where a view would refresh itself on `viewDidAppear`, I thought it would be nice to have `YoshiTableViewMenuItem` support execute a certain block after dismissal, I think this is already supported in a normal `YoshiMenu`

**Comment by quentinR** [comment]
Yeah, it's already supported with a custom YoshiMenu. I'm not sure why you want to use a YoshiTableViewMenuItem.
IMO I would use a YoshiMenu and reload your data or whatever happen in your `viewDidAppear` in the `completion` block. I invite you to check out the [documentation](https://github.com/prolificinteractive/Yoshi#custom-menu) for that. Let me know if it help you!

**Comment by MichaelCampbell** [comment]
@ghvg1313 closing this issue. Please reopen of this is still an issue.
