### ISSUE TITLE
Change .presentViewController in YoshiActionResult to present modally

### ISSUE THREAD

**Issue by atecle** [prolificinteractive/Yoshi#63]
Hey there,

I added a menu item that is supposed to present a UIAlertController with a text field, and the execute action takes the text's input. Here's what that looks like

```swift
import Yoshi

    internal final class TextFieldAlertYoshiMenuItem: YoshiMenu {

        let executionBlock: (String) -> Void
        var title: String
        var subtitle: String?

        required init(title: String = "Debug Feature", subtitle: String? = nil, executionBlock: @escaping (String) -> Void) {
            self.title = title
            self.subtitle = subtitle
            self.executionBlock = executionBlock
        }

        func execute() -> YoshiActionResult {
            let alert = UIAlertController(title: "Some Title", message: "Enter a text", preferredStyle: .alert)
            alert.addTextField { (textField) in
                textField.text = "Some default text"
            }
            alert.addAction(UIAlertAction(title: "OK", style: .default, handler: { [weak alert] (_) in
                let textField = alert?.textFields![0]
                self.executionBlock(textField!.text!)
            }))

            return .presentViewController(alert)
        }
    }
```

Currently`.presentViewController` pushes the provided VC onto the navigation stack. This is in`DebugViewController.swift`

```swift
func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)

        let selectedOption = options[(indexPath as NSIndexPath).row]
        switch selectedOption.execute() {
        case .presentViewController(let viewController):
            navigationController?.pushViewController(viewController, animated: true)
            break
        case .asyncAfterDismissing(let asyncAction):
            completionHandler(asyncAction)
            break
        default:
            return
        }
    }
```

So could we change YoshiActionResult to look like this 

```swift
public enum YoshiActionResult {
    case handled
    case present(UIViewController)
    case push(UIViewController)
    case asyncAfterDismissing(() -> Void)
}
```

and handle those cases accordingly in `DebugViewController`? Can submit a PR for this change if it seems OK.

Thanks!
Adam

**Comment by ghvg1313** [comment]
@atecle You can achieve the same thing using `asyncAfterDismissing`, is there any reason to present a view controller within `DebugViewController` in Yoshi?

**Comment by atecle** [comment]
@ghvg1313 I'm adding a Yoshi menu item to automate creation of test user accounts. I want the user to be able to be able to enter the email of the test account within Yoshi's UI. The interaction I wanted would bring up an `UIAlertController` with a text input. Is it problematic to present a modal on this VC?

**Comment by ghvg1313** [comment]
@atecle It's not, But as a lightweight Debugging tool, I don't want to over-complicate or expose too much flexibility over the navigation stack.
I'm not against the idea, you can make the PR and let's see how it goes

**Comment by atecle** [comment]
Hm I can see that. But I do think that enabling functionality to accept text input easily and execute some code based on it would be a useful feature of a debugging tool. If I found a use case for it, others may as well. I just opened a PR - #64

**Comment by atecle** [comment]
#64 merged, closing
